# Generated by Django 2.0.7 on 2018-07-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('unit_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=200)),
                ('year', models.CharField(choices=[('First_Year_First_Semester', 'First Year First Semester'), ('First_Year_Second_Semester', 'First Year Second Semester'), ('Second_Year_First_Semester', 'Second Year First Semester'), ('Second_Year_Second_Semester', 'Second Year Second Semester'), ('Third_Year_First_Semester', 'Third Year First Semester'), ('Third_Year_Second_Semester', 'Third Year Second Semester'), ('Fourth_Year_First_Semester', 'Fourth Year First Semester'), ('Fourth_Year_Second_Semester', 'Fourth Year Second Semester')], default='First_Year_First_Semester', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Department_Type', models.CharField(choices=[('SCIT', 'School of Computing and Information Technology'), ('COHES', 'Collage of Health Sciences'), ('BBC', 'Business Computing')], default='SCIT', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('other_names', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('other_names', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(max_length=20, null=True, unique=True)),
                ('id_no_Passport', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(upload_to='profile_images')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('parent_Contacts', models.CharField(max_length=255)),
                ('student_Contacts', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('certificates', models.FileField(upload_to='documents')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_course', to='students.Department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='students.Department'),
        ),
    ]
