# Generated by Django 2.0.7 on 2018-07-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1.1, 'First Year First Semester'), (1.2, 'First Year Second Semester'), (2.1, 'Second Year First Semester'), (2.2, 'Second Year Second Semester'), (3.1, 'Third Year First Semester'), (3.2, 'Third Year Second Semester'), (4.1, 'Fourth Year First Semester'), (4.2, 'Fourth Year Second Semester')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('other_names', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(max_length=20, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(upload_to='profile_images')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('parent_contacts', models.CharField(max_length=255)),
                ('student_contacts', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('Certificates', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='students.Department'),
        ),
    ]
