# Generated by Django 2.0.7 on 2018-07-19 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='type',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AddField(
            model_name='department',
            name='dept_code',
            field=models.CharField(default=True, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='dept_name',
            field=models.CharField(default=datetime.datetime(2018, 7, 19, 13, 57, 5, 270438, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='dept_type',
            field=models.CharField(choices=[('BIT', 'Information technology'), ('COHES', 'Collage of health sciences'), ('SCIT', 'Computer science')], default='BIT', max_length=200),
        ),
    ]
