# Generated by Django 2.0.7 on 2018-07-25 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_leave', models.BooleanField(default=False)),
                ('detail', models.TextField(default='no')),
                ('leave_count', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_att', to='students.Department')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stud_image', to='students.Student')),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stud_reg', to='students.Student')),
                ('unit_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_att', to='students.Course')),
            ],
        ),
    ]
