# Generated by Django 2.0.7 on 2018-07-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20180725_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='duration',
        ),
    ]
