# Generated by Django 2.0.7 on 2018-07-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
    ]
